name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/${{ github.actor }}/hdhr-legacy-proxy:latest
        docker push ghcr.io/${{ github.actor }}/hdhr-legacy-proxy:latest
